### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by erfannoury** [google/revisiting-self-supervised#2]
Is it possible for the authors to publish the pretrained models?

**Comment by lucasb-eyer** [comment]
We are looking into it. Stay tuned and subscribe to this issue to get notified.

**Comment by aqibsaeed** [comment]
Any updates on this? Thank you in advance.

**Comment by akolesnikoff** [comment]
Sorry for the delay, links to the models are here: https://colab.research.google.com/drive/1HdApkScZpulQrACrPKZiKYHhy7MeR3iN
