### ISSUE TITLE
Typo in train_and_eval.py?

### ISSUE THREAD

**Issue by rui1996** [google/revisiting-self-supervised#4]
The description of the learning rate scale here is wrong?
https://github.com/google/revisiting-self-supervised/blob/1eac8a76c1b002d74b4b2983739d2e0280f5a09c/train_and_eval.py#L173

Because according to the calculation here:
https://github.com/google/revisiting-self-supervised/blob/1eac8a76c1b002d74b4b2983739d2e0280f5a09c/trainer.py#L73

The lr_factor should be 4 right?

**Comment by lucasb-eyer** [comment]
You are right, this looks like a mistake in the documentation, it should say `then actual lr=0.4.` Good catch! Do you want to make a PR?

**Comment by rui1996** [comment]
Thanks for you reply. You could just edit it.
