### ISSUE TITLE
Code for logistic regression by L-BFGS

### ISSUE THREAD

**Issue by mbsariyildiz** [google/revisiting-self-supervised#5]
Hello! 

Congratulations for the CVPR paper, and thanks for sharing your implementation.
Is the code for training logistic regression classifiers using L-BFGS available here in the repo? If it is not, can you please tell me how implemented that? 

Regards.

**Comment by lucasb-eyer** [comment]
Hi, sorry for the late reply. No, we have not open-sourced it in this repo. It was a standalone separate tool, but essentially what it does is pre-compute the embeddings of the full dataset, and then run them through the [`scipy.minimize`](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-lbfgsb.html) L-BFGS wrapper.

**Comment by mbsariyildiz** [comment]
Thanks for your reply! I use [scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html) to learn linear regression classifiers, but that is taking quite some time. Perhaps you don't remember the timings, but still are there any practical advices you can share with me?

**Comment by lucasb-eyer** [comment]
Yeah, I remember linear (logistic) regression took a long time to converge, we even reported this in our paper, see Figure 8 of the paper.

I believe having read a paper some time after ours that reported linear SVM to converge much faster, you might try that, it should be easy as you are using sklearn anyways? We have not tried it, but I would be curious to hear about your experience if you do!

**Comment by mbsariyildiz** [comment]
Thanks! I was actually referring too training linear regression classifiers by L-BFGS.

The Figure-8 is interesting and I think it suggests that we need more practical ways to evaluate if representations are linearly separable or not. Why do we need data augmentation at test time anyway?

You mean one-vs-all SVM on Imagenet? For COCO, on a machine with 32 CPU cores, searching for 50 different cost parameters by doing 3-fold cross-validation already takes 20 hours.
