### ISSUE TITLE
How to prepare the dataset?

### ISSUE THREAD

**Issue by doantientai** [google/revisiting-self-supervised#7]
Hi, thank you for interesting work! I am trying to reproduce the experiment in my PC using single GPU. 

In the parameters for training the model, I saw   `--dataset_dir <PREPROCESSED_IMAGENET_PATH>`. However, I couldn't find any instruction on how to prepare what inside this folder. Could you please explain it a little bit?

Thank you!

**Comment by lucasb-eyer** [comment]
[We explain this in the README here](https://github.com/google/revisiting-self-supervised#preparing-data), basically use the tf.slim scripts for preparation.
